import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { configuredReminders, validateReminders, upcomingEventAlerts, claimAlertNotice } = require('../node_modules/.tmp/task-tests/services/reminders.js');
const { financialComposition, financialDate, currentFinanceTime, validFinanceTime, compareFinancialDate } = require('../node_modules/.tmp/task-tests/services/finance.js');
const { googleCalendarUrl } = require('../node_modules/.tmp/task-tests/services/calendarService.js');
const { LocalDocumentRepository } = require('../node_modules/.tmp/task-tests/repositories/documentsRepository.js');
const { TemporaryDocumentFiles } = require('../node_modules/.tmp/task-tests/services/documentFiles.js');
const { taskNotifications } = require('../node_modules/.tmp/task-tests/services/taskNotifications.js');
const event = { id: 'e', casoId: 'real-id', titulo: 'Reunión', tipo: 'Reunión', fecha: '2026-10-03', hora: '07:00' };
const now = new Date('2026-10-02T16:15:00Z');
test('recordatorios personalizados, compatibilidad, validación y texto único para Calendar', () => {
  assert.deepEqual(configuredReminders(event), []);
  assert.deepEqual(configuredReminders({ ...event, recordatorios: { unDiaAntes: true, unaHoraAntes: true } }), [{ cantidad: 1, unidad: 'días' }, { cantidad: 1, unidad: 'horas' }]);
  const items = [{ cantidad: 3, unidad: 'días' }, { cantidad: 2, unidad: 'horas' }, { cantidad: 30, unidad: 'minutos' }];
  assert.deepEqual(validateReminders(items), items);
  for (const invalid of [[{ cantidad: 0, unidad: 'horas' }], [{ cantidad: -1, unidad: 'días' }], [{ cantidad: 0.5, unidad: 'horas' }], [{ cantidad: 100, unidad: 'semanas' }], [{ cantidad: 1, unidad: 'horas' }, { cantidad: 60, unidad: 'minutos' }]]) assert.throws(() => validateReminders(invalid));
  const configured = { ...event, recordatorios: { unDiaAntes: true, unaHoraAntes: true, personalizados: items } };
  assert.deepEqual(configuredReminders(configured), items);
  const description = new URL(googleCalendarUrl(configured)).searchParams.get('details');
  for (const label of ['3 días antes', '2 horas antes', '30 minutos antes']) assert.ok(description.includes(label));
  assert.deepEqual(configuredReminders({ ...configured, recordatorios: { personalizados: [] } }), []);
});
test('alertas: reunión mañana, umbrales múltiples, sin recordatorios y sesión aislada', () => {
  const configured = { ...event, recordatorios: { personalizados: [{ cantidad: 1, unidad: 'días' }, { cantidad: 1, unidad: 'horas' }] } };
  assert.equal(upcomingEventAlerts([event], now).length, 0);
  const first = upcomingEventAlerts([configured], now);
  assert.equal(first.length, 1);
  assert.equal(first[0].label, 'Reunión en 18 h 45 min');
  assert.equal(upcomingEventAlerts([{ ...configured, realizado: true }], now).length, 0);
  assert.equal(upcomingEventAlerts([configured], new Date('2026-10-04T00:00:00Z')).length, 0);
  const second = upcomingEventAlerts([configured], new Date('2026-10-03T10:30:00Z'));
  assert.notEqual(first[0].noticeKey, second[0].noticeKey);
  const store = new Map();
  globalThis.sessionStorage = { getItem: key => store.get(key), setItem: (key, value) => store.set(key, value) };
  assert.equal(claimAlertNotice('estudio-A', first[0].noticeKey), true);
  assert.equal(claimAlertNotice('estudio-A', first[0].noticeKey), false);
  assert.equal(claimAlertNotice('estudio-A', second[0].noticeKey), true);
  assert.equal(claimAlertNotice('estudio-B', first[0].noticeKey), true);
  const tasks = [{ id: 't', casoId: 'real-id', estado: 'Pendiente', titulo: 'Tarea', prioridad: 'Normal', fechaLimite: '2026-10-03', horaLimite: '07:00', createdAt: now.toISOString() }];
  assert.equal(taskNotifications(tasks, now).relevant.length, 1);
  assert.equal(taskNotifications([{ ...tasks[0], estado: 'Completada' }], now).relevant.length, 0);
});
test('finanzas: caja, reembolsos sin doble conteo y déficit real', () => {
  const totals = { totalCobrado: 100, totalGastos: 65, totalReembolsado: 12, saldoPendiente: 400, gastosPendientes: 33 };
  assert.deepEqual(financialComposition(totals), { utilidad: 47, gastos: 53, porCobrar: 433 });
  assert.deepEqual(financialComposition({ ...totals, totalReembolsado: 45, gastosPendientes: 0 }), { utilidad: 80, gastos: 20, porCobrar: 400 });
  assert.equal(financialComposition({ ...totals, totalCobrado: 0 }).utilidad, -53);
  assert.equal(financialComposition({ totalCobrado: 0, totalGastos: 0, totalReembolsado: 0, saldoPendiente: 0, gastosPendientes: 0 }).utilidad, 0);
});
test('fecha/hora: registros antiguos, HH:mm sin segundos y orden', () => {
  assert.equal(financialDate({ fecha: '2026-10-02' }), '02/10/2026');
  assert.equal(financialDate({ fecha: '2026-10-02', hora: '19:45' }), '02/10/2026 · 19:45');
  assert.equal(currentFinanceTime(new Date('2026-10-02T23:45:30Z')), '19:45');
  for (const value of ['25:00', '12:99', '19:45:10']) assert.equal(validFinanceTime(value), false);
  assert.ok(validFinanceTime('19:45') && validFinanceTime(''));
  const list = [{ fecha: '2026-10-02' }, { fecha: '2026-10-02', hora: '19:45' }].sort(compareFinancialDate);
  assert.equal(list[0].hora, '19:45');
});
test('documentos: usa caso real activo, aislamiento por estudio y metadatos tras recarga', async () => {
  const storage = new Map();
  globalThis.localStorage = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) };
  const active = { getCaseById: async id => id === 'real-id' ? { id, nombre: 'Prestamo' } : null };
  const exists = async id => Boolean(await active.getCaseById(id));
  const a = new LocalDocumentRepository(new TemporaryDocumentFiles(), exists, 'docs:A');
  const b = new LocalDocumentRepository(new TemporaryDocumentFiles(), exists, 'docs:B');
  const doc = await a.addDocument('real-id', { nombre: 'Contrato', categoria: 'Contrato' }, new File(['%PDF-1.4 test'], 'test.pdf', { type: 'application/pdf' }));
  assert.equal(doc.casoId, 'real-id');
  assert.equal((await b.getDocuments()).length, 0);
  assert.equal((await a.getDocuments('otro-id')).length, 0);
  await assert.rejects(() => b.getFileUrl('real-id', doc.id), /pertenece/);
  const reload = new LocalDocumentRepository(new TemporaryDocumentFiles(), exists, 'docs:A');
  assert.equal((await reload.getDocuments())[0].id, doc.id);
  assert.equal(await reload.getFileUrl('real-id', doc.id), null);
});
